services:
  postgres:
    image: postgres:18-alpine
    container_name: nx-shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nx-shop
      POSTGRES_PASSWORD: nx-shop
      POSTGRES_DB: nx-shop
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nx-shop -d nx-shop']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
